---
title: "Building a personal quarto webpage"
format:
  html: default
---

### Overview

We will create our own personal quarto webpages to give you a forum for showing your data science portfolio, featuring projects from SDS 264 in addition to things you've worked on in other classes, independently, etc.

We will follow the [excellent set of instructions](https://ucsb-meds.github.io/creating-quarto-websites/) prepared by Samantha Csik and others as part of the Bren School of Environmental Science & Management’s Master of Environmental Data Science (MEDS) program.

I have found success starting at the top of working my way carefully through the steps outlined.  I cannot emphasize this enough: **be sure to NOT speed through the steps, but follow even the small, subtle suggestions, and stop and appreciate the useful insights given at various points in the process!**  Continue all the way through the end of the website!


### Specifics

You will publish a personal quarto webpage that contains basic information about yourself, as well as a menu bar that contains, at a minimum, a link to your work from Mini-Project 1 on maps and Mini-Project 2 on data acquisition, and a link to your source code on GitHub.

[Here](https://proback.github.io/) is a pretty basic example that I put together.  I'm hoping you'll put together something more impressive -- taking advantage of features in quarto to create a look that you're excited about and an organization and layout that cleanly highlights your good work.  Check out this [rubric](https://drive.google.com/file/d/1UB9PEopUoIyl6DWCSN03pM5S_S7Awi71/view?usp=sharing) for Mini-Project 3.  


### Submission and Timeline

Mini-Project 3 must be submitted on moodle by **11:00 PM on Fri Nov 1**.  All I need is a url for your webpage, which should then have a link to your R code in GitHub.  If you choose not to make your webpage public at this time, please add me as a collaborator to your GitHub repository so that I can see your code and generate your webpage.
