---
title: "Mini-Project 2: Simulation"
format:
  html: default
---
  
```{r}
#| include: false

library(tidyverse)
```

### Overview

You will conduct a small simulation study which does one of these tasks:

a) investigates the effects of a factor or two on the power of a statistical test

b) investigates the effects of condition violations on a statistical test, as measured by coverage rate, confidence interval width, type I error rate, etc.

c) conducts a randomization-type test by simulating behavior under the null hypothesis

d) develops a lineup protocol for visual inference, as in [this paper](https://drive.google.com/file/d/1J14APUZkbEYBXbGdasaGyK0Dxjc4R5Gn/view?usp=sharing) by Adam Loy from Carleton

Your simulation study should contain the following elements:

- at least 1 function you've written
- at least 1 loop (it can be imperative or functional, or you can try it both ways)
- at least 1 illustrative, well-labeled plot
- a description of what insights can be gained from your plot(s)


### Timeline

Mini-Project 2 must be submitted on moodle by **11:00 PM on Fri Mar 22**.    Ideally, you'd add a tab to your quarto webpage with Mini-Project 2, then you can just submit your URL (as long as your code is linked to the page).  You can alternatively submit a knitted pdf showing your code and output.


### Additional Notes

You may choose to work solo or with a partner.  If you choose to work with a partner, I ask each of you to hand in your final product (even though it's likely the same thing) and also to describe your role in the project - was the coding 50/50? who generated ideas at various stages? who designed the final product? etc.  If you work with someone else, ideally both of you would upload the final product to your own quarto webpages (with attribution to your co-author)
